import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import '@radix-ui/themes/styles.css';
import '../globals.css'
import { Theme } from '@radix-ui/themes';
import Navbar from '../Components/Navbar/Navbar';
import Footer from '../Components/Footer/Footer';

const inter = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hostel Booking',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Theme>
      <body className={`${inter.className} ` }>
        <Navbar />

        <div className='pt-16'>
        {children}

        </div>
        <Footer />

        
      </body>

      </Theme>
    </html>
  )
}
