import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import '@radix-ui/themes/styles.css';
import '../globals.css'
import { Theme } from '@radix-ui/themes';
import { ClerkProvider } from '@clerk/nextjs';

const inter = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Hostel Booking',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
        <ClerkProvider>

      <body className={inter.className}>
        <div className="h-screen bg-[url('/authback.jpg')] bg-cover">
          {children}
        </div>

        </body>
        </ClerkProvider>

      
    </html>
  )
}
